export const OrderStatus = {
  ABERTO: 'ABERTO',
  CARREGADO: 'CARREGADO',
  EM_TRANSITO: 'EM_TRANSITO',
  ENTREGUE: 'ENTREGUE',
  CANCELADO: 'CANCELADO',
  DEVOLVIDO: 'DEVOLVIDO'
};

export const LoadStatus = {
  PENDENTE: 'PENDENTE',
  AGENDADO: 'AGENDADO',
  CARREGANDO: 'CARREGANDO',
  CARREGADO: 'CARREGADO',
  EM_TRANSITO: 'EM_TRANSITO',
  ENTREGUE: 'ENTREGUE',
  CANCELADO: 'CANCELADO',
  RETORNADO: 'RETORNADO'
}
