name: Lint and Prettier Check

on:
  pull_request:
    branches:
      - development

jobs:
  lint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # ajuste conforme sua versão do Node.js

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
